source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target ‘shenzhoudc-iPhone’ do
    pod 'AFNetworking', '~> 3.0'
    pod 'JSONModel'
    pod 'Masonry'
    pod 'IQKeyboardManager'
    pod 'SDWebImage', '~>3.8'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'HMImagePicker', '~> 1.0.4'
    pod 'MJRefresh'
    pod 'ZYSideSlipFilter', '~> 0.5.0'
    pod 'SDCycleScrollView','~> 1.64'
    pod 'ZFPlayer'
    pod 'FDFullscreenPopGesture'
#    pod 'ZFDownload'
    pod 'SVProgressHUD'
     pod 'LBXScan', '1.1.1'

end
post_install do |installer|
copy_pods_resources_path = "Pods/Target Support Files/Pods-FuelCardApp/Pods-FuelCardApp-resources.sh"
string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'
text = File.read(copy_pods_resources_path)
new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
end
