source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'WashingMachine' do
    pod 'IQKeyboardManager', '5.0.8'
    pod 'MBProgressHUD', '1.1.0'
    pod 'HMImagePicker', '1.0.4'
    pod 'MJRefresh', '3.1.15.3'
    pod 'Alamofire', '4.8.0'
    pod 'Kingfisher', '4.10.1'
    pod 'SwiftyJSON', '4.2.0'
    pod 'HandyJSON', '5.0.2'
    pod 'SnapKit', '4.2.0'
    pod 'RxSwift', '5.0.1'
    pod 'RxCocoa', '5.0.1'
    
    #    pod 'Spring', '1.0.5'
    pod 'SwiftGifOrigin', '1.6.1'
    pod 'KeychainSwift', '19.0.0'
end


#Installing Alamofire 4.7.1 (was 4.6.0)
#Using HMImagePicker (1.0.4)
#Using HandyJSON (4.0.0-beta.1)
#Installing IQKeyboardManager 5.0.8 (was 5.0.7)
#Installing Kingfisher 4.6.4 (was 4.6.1)
#Using MBProgressHUD (1.1.0)
#Using MJRefresh (3.1.15.3)
#Installing RxCocoa 4.1.2 (was 4.1.1)
#Installing RxSwift 4.1.2 (was 4.1.1)
#Using SnapKit (4.0.0)
#Using Spring (1.0.5)
#Using SwiftGifOrigin (1.6.1)
#Using SwiftyJSON (4.0.0)

#
#    pod 'IQKeyboardManager', '5.0.8'
#    pod 'MBProgressHUD', '1.1.0'
#    pod 'HMImagePicker', '1.0.4'
#    pod 'MJRefresh', '3.1.15.3'
#    pod 'Alamofire', '4.8.0'
#    pod 'Kingfisher', '4.10.1'
#    pod 'SwiftyJSON', '4.0.0'
#    pod 'HandyJSON', '4.1.3'
#    pod 'SnapKit', '4.0.0'
#    pod 'Spring', '1.0.5'
#    pod 'SwiftGifOrigin', '1.6.1'
#    pod 'RxSwift', '4.1.2'
#    pod 'RxCocoa', '4.1.2'
